title: Open Buro — Tech Sprint n°1
description: Inter-App Communication via Intents & Capabilities — File Picker
remote_theme: just-the-docs/just-the-docs

url: ""
baseurl: "/TechSprint-n-01-april-20206-FilePicker"

permalink: pretty

plugins:
  - jekyll-remote-theme

aux_links:
  "GitHub":
    - "https://github.com/openburo/TechSprint-n-01-april-20206-FilePicker"

nav_enabled: true
search_enabled: true

footer_content: "Hackathon Open Buro — Avril 2026"

color_scheme: blue
